sudo: false

language: node_js
cache: yarn
node_js:
  - node
  - "10"
  - "8"

script: npm run test:coverage

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
